name: Build PicoWPortal

on:
  workflow_dispatch:
    inputs:
      wifi_ssid:
        description: 'Wi-Fi Network Name (SSID)'
        required: true
        type: string
      wifi_password:
        description: 'Wi-Fi Password'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Compiler & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake ninja-build libstdc++-arm-none-eabi-newlib

      - name: Checkout Pico SDK
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk
          submodules: recursive

      - name: Build UF2 File
        run: |
          cmake -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk -DBOARD=pico_w -DWIFI_SSID="${{ inputs.wifi_ssid }}" -DWIFI_PASSWORD="${{ inputs.wifi_password }}" -B ./build
          cmake --build ./build --config Release

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PicoWPortal-UF2
          path: build/PicoWPortal.uf2
